//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantPortal.WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MerchantIBEntities : DbContext
    {
        public MerchantIBEntities()
            : base("name=MerchantIBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Transaction> Transactions { get; set; }
    
        public virtual ObjectResult<Transaction> Get_Sell_Transaction(string merchant_ID, string terminal_ID, string currency_Code, string mct_trnxn_id, string language_Code, string mct_ref_id, string merVar1, string merVar2, string merVar3, string merVar4, string merVar5, string merVar6, string merVar7, string merVar8, string product_Type, string return_URL, string mct_trnxn_Amount)
        {
            var merchant_IDParameter = merchant_ID != null ?
                new ObjectParameter("Merchant_ID", merchant_ID) :
                new ObjectParameter("Merchant_ID", typeof(string));
    
            var terminal_IDParameter = terminal_ID != null ?
                new ObjectParameter("Terminal_ID", terminal_ID) :
                new ObjectParameter("Terminal_ID", typeof(string));
    
            var currency_CodeParameter = currency_Code != null ?
                new ObjectParameter("Currency_Code", currency_Code) :
                new ObjectParameter("Currency_Code", typeof(string));
    
            var mct_trnxn_idParameter = mct_trnxn_id != null ?
                new ObjectParameter("mct_trnxn_id", mct_trnxn_id) :
                new ObjectParameter("mct_trnxn_id", typeof(string));
    
            var language_CodeParameter = language_Code != null ?
                new ObjectParameter("Language_Code", language_Code) :
                new ObjectParameter("Language_Code", typeof(string));
    
            var mct_ref_idParameter = mct_ref_id != null ?
                new ObjectParameter("mct_ref_id", mct_ref_id) :
                new ObjectParameter("mct_ref_id", typeof(string));
    
            var merVar1Parameter = merVar1 != null ?
                new ObjectParameter("MerVar1", merVar1) :
                new ObjectParameter("MerVar1", typeof(string));
    
            var merVar2Parameter = merVar2 != null ?
                new ObjectParameter("MerVar2", merVar2) :
                new ObjectParameter("MerVar2", typeof(string));
    
            var merVar3Parameter = merVar3 != null ?
                new ObjectParameter("MerVar3", merVar3) :
                new ObjectParameter("MerVar3", typeof(string));
    
            var merVar4Parameter = merVar4 != null ?
                new ObjectParameter("MerVar4", merVar4) :
                new ObjectParameter("MerVar4", typeof(string));
    
            var merVar5Parameter = merVar5 != null ?
                new ObjectParameter("MerVar5", merVar5) :
                new ObjectParameter("MerVar5", typeof(string));
    
            var merVar6Parameter = merVar6 != null ?
                new ObjectParameter("MerVar6", merVar6) :
                new ObjectParameter("MerVar6", typeof(string));
    
            var merVar7Parameter = merVar7 != null ?
                new ObjectParameter("MerVar7", merVar7) :
                new ObjectParameter("MerVar7", typeof(string));
    
            var merVar8Parameter = merVar8 != null ?
                new ObjectParameter("MerVar8", merVar8) :
                new ObjectParameter("MerVar8", typeof(string));
    
            var product_TypeParameter = product_Type != null ?
                new ObjectParameter("Product_Type", product_Type) :
                new ObjectParameter("Product_Type", typeof(string));
    
            var return_URLParameter = return_URL != null ?
                new ObjectParameter("Return_URL", return_URL) :
                new ObjectParameter("Return_URL", typeof(string));
    
            var mct_trnxn_AmountParameter = mct_trnxn_Amount != null ?
                new ObjectParameter("mct_trnxn_Amount", mct_trnxn_Amount) :
                new ObjectParameter("mct_trnxn_Amount", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Transaction>("Get_Sell_Transaction", merchant_IDParameter, terminal_IDParameter, currency_CodeParameter, mct_trnxn_idParameter, language_CodeParameter, mct_ref_idParameter, merVar1Parameter, merVar2Parameter, merVar3Parameter, merVar4Parameter, merVar5Parameter, merVar6Parameter, merVar7Parameter, merVar8Parameter, product_TypeParameter, return_URLParameter, mct_trnxn_AmountParameter);
        }
    
        public virtual ObjectResult<Transaction> Get_Sell_Transaction(string merchant_ID, string terminal_ID, string currency_Code, string mct_trnxn_id, string language_Code, string mct_ref_id, string merVar1, string merVar2, string merVar3, string merVar4, string merVar5, string merVar6, string merVar7, string merVar8, string product_Type, string return_URL, string mct_trnxn_Amount, MergeOption mergeOption)
        {
            var merchant_IDParameter = merchant_ID != null ?
                new ObjectParameter("Merchant_ID", merchant_ID) :
                new ObjectParameter("Merchant_ID", typeof(string));
    
            var terminal_IDParameter = terminal_ID != null ?
                new ObjectParameter("Terminal_ID", terminal_ID) :
                new ObjectParameter("Terminal_ID", typeof(string));
    
            var currency_CodeParameter = currency_Code != null ?
                new ObjectParameter("Currency_Code", currency_Code) :
                new ObjectParameter("Currency_Code", typeof(string));
    
            var mct_trnxn_idParameter = mct_trnxn_id != null ?
                new ObjectParameter("mct_trnxn_id", mct_trnxn_id) :
                new ObjectParameter("mct_trnxn_id", typeof(string));
    
            var language_CodeParameter = language_Code != null ?
                new ObjectParameter("Language_Code", language_Code) :
                new ObjectParameter("Language_Code", typeof(string));
    
            var mct_ref_idParameter = mct_ref_id != null ?
                new ObjectParameter("mct_ref_id", mct_ref_id) :
                new ObjectParameter("mct_ref_id", typeof(string));
    
            var merVar1Parameter = merVar1 != null ?
                new ObjectParameter("MerVar1", merVar1) :
                new ObjectParameter("MerVar1", typeof(string));
    
            var merVar2Parameter = merVar2 != null ?
                new ObjectParameter("MerVar2", merVar2) :
                new ObjectParameter("MerVar2", typeof(string));
    
            var merVar3Parameter = merVar3 != null ?
                new ObjectParameter("MerVar3", merVar3) :
                new ObjectParameter("MerVar3", typeof(string));
    
            var merVar4Parameter = merVar4 != null ?
                new ObjectParameter("MerVar4", merVar4) :
                new ObjectParameter("MerVar4", typeof(string));
    
            var merVar5Parameter = merVar5 != null ?
                new ObjectParameter("MerVar5", merVar5) :
                new ObjectParameter("MerVar5", typeof(string));
    
            var merVar6Parameter = merVar6 != null ?
                new ObjectParameter("MerVar6", merVar6) :
                new ObjectParameter("MerVar6", typeof(string));
    
            var merVar7Parameter = merVar7 != null ?
                new ObjectParameter("MerVar7", merVar7) :
                new ObjectParameter("MerVar7", typeof(string));
    
            var merVar8Parameter = merVar8 != null ?
                new ObjectParameter("MerVar8", merVar8) :
                new ObjectParameter("MerVar8", typeof(string));
    
            var product_TypeParameter = product_Type != null ?
                new ObjectParameter("Product_Type", product_Type) :
                new ObjectParameter("Product_Type", typeof(string));
    
            var return_URLParameter = return_URL != null ?
                new ObjectParameter("Return_URL", return_URL) :
                new ObjectParameter("Return_URL", typeof(string));
    
            var mct_trnxn_AmountParameter = mct_trnxn_Amount != null ?
                new ObjectParameter("mct_trnxn_Amount", mct_trnxn_Amount) :
                new ObjectParameter("mct_trnxn_Amount", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Transaction>("Get_Sell_Transaction", mergeOption, merchant_IDParameter, terminal_IDParameter, currency_CodeParameter, mct_trnxn_idParameter, language_CodeParameter, mct_ref_idParameter, merVar1Parameter, merVar2Parameter, merVar3Parameter, merVar4Parameter, merVar5Parameter, merVar6Parameter, merVar7Parameter, merVar8Parameter, product_TypeParameter, return_URLParameter, mct_trnxn_AmountParameter);
        }
    
        public virtual ObjectResult<PROC_REQ_FROM_MERCHANT_SELL_TRANS_VERIFY_Result> Verify_Sell_Transaction(string action, string merchant_ID, string mct_ref_id)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var merchant_IDParameter = merchant_ID != null ?
                new ObjectParameter("Merchant_ID", merchant_ID) :
                new ObjectParameter("Merchant_ID", typeof(string));
    
            var mct_ref_idParameter = mct_ref_id != null ?
                new ObjectParameter("mct_ref_id", mct_ref_id) :
                new ObjectParameter("mct_ref_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_REQ_FROM_MERCHANT_SELL_TRANS_VERIFY_Result>("Verify_Sell_Transaction", actionParameter, merchant_IDParameter, mct_ref_idParameter);
        }
    }
}
